export default Object.freeze([
  {category:'-', iconName:'food', text:'餐饮'},
  {category:'-', iconName:'shopping', text:'购物'},
  {category:'-', iconName:'house', text:'住房'},
  {category:'-', iconName:'clothes', text:'衣服'},
  {category:'-', iconName:'travel', text:'旅行'},
  {category:'-', iconName:'entertainment', text:'娱乐'},
  {category:'-', iconName:'electronic', text:'电子'},
  {category:'-', iconName:'study', text:'学习'},
  {category:'-', iconName:'transportation', text:'交通'},
  {category:'+', iconName:'salary', text:'工资'},
  {category:'+', iconName:'manage-money', text:'理财'},
  {category:'+', iconName:'part-time', text:'兼职'},
  {category:'+', iconName:'other', text:'其他'},
]);